services:
  sgivu-mysql:
    container_name: sgivu-mysql
    image: mysql:8
    command: --mysql-native-password=ON
    ports:
      - "3306:3306"
    restart: always
    env_file: .env.dev
    networks:
      - sgivu-network
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

  sgivu-postgres:
    container_name: sgivu-postgres
    image: postgres:16
    ports:
      - "5432:5432"
    restart: always
    env_file: .env.dev
    networks:
      - sgivu-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  sgivu-redis:
    container_name: sgivu-redis
    image: redis:7
    command: >
      sh -c "redis-server --requirepass \"$REDIS_PASSWORD\""
    env_file: .env.dev
    ports:
      - "6379:6379"
    restart: always
    networks:
      - sgivu-network
    volumes:
      - redis-data:/data

  sgivu-config:
    container_name: sgivu-config
    image: stevenrq/sgivu-config:v1
    ports:
      - "8888:8888"
    restart: always
    networks:
      - sgivu-network
    volumes:
      - ../../../../sgivu-config-repo:/config-repo
    environment:
      - SPRING_PROFILES_ACTIVE=native # Utilice el perfil 'nativo' para leer desde el sistema de archivos local o 'git' para el repositorio de Git
      - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:/config-repo # Ruta del sistema de archivos local para el perfil 'nativo'

  sgivu-discovery:
    container_name: sgivu-discovery
    image: stevenrq/sgivu-discovery:v1
    ports:
      - "8761:8761"
    restart: always
    networks:
      - sgivu-network
    env_file: .env.dev

  sgivu-zipkin:
    container_name: sgivu-zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    restart: always
    networks:
      - sgivu-network
    env_file: .env.dev
    depends_on:
      - sgivu-mysql

  sgivu-auth:
    container_name: sgivu-auth
    image: stevenrq/sgivu-auth:v1
    ports:
      - "9000:9000"
    restart: always
    networks:
      - sgivu-network
    env_file: .env.dev
    depends_on:
      - sgivu-postgres
      - sgivu-config
      - sgivu-discovery

  sgivu-user:
    container_name: sgivu-user
    image: stevenrq/sgivu-user:v1
    ports:
      - "8081:8081"
    restart: always
    networks:
      - sgivu-network
    env_file: .env.dev
    depends_on:
      - sgivu-postgres
      - sgivu-config
      - sgivu-discovery
      - sgivu-auth

  sgivu-client:
    container_name: sgivu-client
    image: stevenrq/sgivu-client:v1
    ports:
      - "8082:8082"
    restart: always
    networks:
      - sgivu-network
    env_file: .env.dev
    depends_on:
      - sgivu-postgres
      - sgivu-config
      - sgivu-discovery
      - sgivu-auth

  sgivu-vehicle:
    container_name: sgivu-vehicle
    image: stevenrq/sgivu-vehicle:v1
    ports:
      - "8083:8083"
    restart: always
    networks:
      - sgivu-network
    env_file: .env.dev
    depends_on:
      - sgivu-postgres
      - sgivu-config
      - sgivu-discovery
      - sgivu-auth

  sgivu-purchase-sale:
    container_name: sgivu-purchase-sale
    image: stevenrq/sgivu-purchase-sale:v1
    ports:
      - "8084:8084"
    restart: always
    networks:
      - sgivu-network
    env_file: .env.dev
    depends_on:
      - sgivu-postgres
      - sgivu-config
      - sgivu-discovery
      - sgivu-auth

  sgivu-ml:
    container_name: sgivu-ml
    image: stevenrq/sgivu-ml:v1
    ports:
      - "8000:8000"
    restart: always
    networks:
      - sgivu-network
    env_file: .env.dev
    depends_on:
      - sgivu-postgres
      - sgivu-auth
      - sgivu-client
      - sgivu-gateway
      - sgivu-user
      - sgivu-vehicle
      - sgivu-purchase-sale

  sgivu-gateway:
    container_name: sgivu-gateway
    image: stevenrq/sgivu-gateway:v1
    ports:
      - "8080:8080"
    restart: always
    networks:
      - sgivu-network
    env_file: .env.dev
    depends_on:
      - sgivu-config
      - sgivu-discovery
      - sgivu-auth
      - sgivu-redis

networks:
  sgivu-network:
    driver: bridge

volumes:
  mysql-data:
  postgres-data:
  redis-data:
